create table ANIME
(
    code           bigint generated by default as identity,
    title          varchar2(100) unique,
    thumb          varchar2(200),
    originaltitle  varchar2(100),
    director       varchar2(100),
    production     varchar2(100),
    genre          varchar2(100),
    classification varchar2(50),
    airingyear     int,
    airingdate     varchar2(50),
    grade          varchar2(50),
    episodes       varchar2(50),
    primary key (code)
);

create table MEMBER
(
    id bigint generated by default as identity,
    uid varchar2(50) unique,
    upw varchar2(200) not null,
    nickName varchar2(50) unique,
    regDate date not null,
    role varchar2(10) not null,
    primary key (id)
);

create table COMMENT
(
    no bigint generated by default as identity,
    code bigint,
    nickName varchar2(50),
    comment varchar2(200),
    primary key (no)
);
